In [471]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.metrics import confusion_matrix
from sklearn import linear_model
from sklearn import metrics
from sklearn.model_selection import GridSearchCV
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve

import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from skimage import feature
from imutils import build_montages
from imutils import paths
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [472]:
import glob
control_file=sorted(glob.glob("data/processed/control/*.csv"))
df1 = pd.DataFrame()
print(len(control_file))
for i in range(len(control_file)):
    df1=df1.append(pd.read_csv(control_file[i]))
df1['label']=0
print(df1.shape)
df1.head()

15
(15, 101)

,X_S_Mean,Y_S_Mean,Z_S_Mean,Pressure_S_Mean,GripAngle_S_Mean,Timestamp_S_Mean,TestID_S_Mean,X_D_Mean,Y_D_Mean,Z_D_Mean,...,totalPath_D,RadMax_S,RadMax_D,Xmax_S,Ymax_S,AR_S,Xmax_D,Ymax_D,AR_D,label
0,199.736230,204.876649,0.721490,884.200931,794.317300,1.732656e+09,0.0,180.819240,187.094259,0.488751,...,1704.523001,201.039797,167.502239,371,337,0.908356,286,262,0.916084,0
0,191.760360,213.143844,0.727928,787.918619,782.852853,1.732477e+09,0.0,200.569970,213.618318,0.559760,...,2161.128124,198.156504,203.039405,343,337,0.982507,365,336,0.920548,0
0,230.687263,252.600152,0.717144,843.550013,903.502152,1.300956e+06,0.0,214.136997,247.773867,0.750570,...,2425.170706,227.008810,225.800797,414,379,0.915459,406,379,0.933498,0
0,196.866048,221.196286,0.689655,894.425729,1043.504642,3.010884e+05,0.0,193.234416,215.691976,0.778515,...,2208.740501,201.022387,206.475180,370,341,0.921622,376,337,0.896277,0
0,193.465046,205.356636,0.626140,917.348531,824.533941,1.732871e+09,0.0,181.697062,196.308004,0.500507,...,1807.705443,200.010000,192.166594,370,342,0.924324,298,341,1.144295,0

In [473]:
park_file=sorted(glob.glob("data/processed/parkinson/*.csv"))
df2 = pd.DataFrame()
print(len(park_file))
for i in range(len(park_file)):
    df2=df2.append(pd.read_csv(park_file[i]))
df2['label']=1
print(df2.shape)
df2.head()

57
(57, 101)

,X_S_Mean,Y_S_Mean,Z_S_Mean,Pressure_S_Mean,GripAngle_S_Mean,Timestamp_S_Mean,TestID_S_Mean,X_D_Mean,Y_D_Mean,Z_D_Mean,...,totalPath_D,RadMax_S,RadMax_D,Xmax_S,Ymax_S,AR_S,Xmax_D,Ymax_D,AR_D,label
0,216.050260,227.548094,0.0,716.772747,1047.253033,6.815689e+07,0.0,212.515815,203.214255,0.0,...,3144.388507,201.638290,219.968180,369,338,0.915989,345,323,0.936232,1
0,194.095757,193.762615,0.0,621.284977,1491.513761,6.976263e+07,0.0,201.311927,213.577982,0.0,...,2091.746863,169.198109,210.278387,282,267,0.946809,358,327,0.913408,1
0,202.118771,211.504437,0.0,715.310580,1602.197952,7.092382e+07,0.0,201.356314,217.479863,0.0,...,2134.005270,147.800541,199.699775,232,214,0.922414,359,323,0.899721,1
0,196.062672,214.769654,0.0,747.818032,1410.698186,7.168989e+07,0.0,202.881253,200.057724,0.0,...,2119.919460,218.709853,209.038274,386,352,0.911917,389,322,0.827763,1
0,190.706580,191.584016,0.0,741.219430,1697.243716,7.501272e+07,0.0,193.982208,207.726348,0.0,...,2304.682579,175.328264,207.154532,294,268,0.911565,366,344,0.939891,1

In [474]:
df=pd.concat([df1, df2],axis=0)
print(df.shape)
df.head()

(72, 101)

,X_S_Mean,Y_S_Mean,Z_S_Mean,Pressure_S_Mean,GripAngle_S_Mean,Timestamp_S_Mean,TestID_S_Mean,X_D_Mean,Y_D_Mean,Z_D_Mean,...,totalPath_D,RadMax_S,RadMax_D,Xmax_S,Ymax_S,AR_S,Xmax_D,Ymax_D,AR_D,label
0,199.736230,204.876649,0.721490,884.200931,794.317300,1.732656e+09,0.0,180.819240,187.094259,0.488751,...,1704.523001,201.039797,167.502239,371,337,0.908356,286,262,0.916084,0
0,191.760360,213.143844,0.727928,787.918619,782.852853,1.732477e+09,0.0,200.569970,213.618318,0.559760,...,2161.128124,198.156504,203.039405,343,337,0.982507,365,336,0.920548,0
0,230.687263,252.600152,0.717144,843.550013,903.502152,1.300956e+06,0.0,214.136997,247.773867,0.750570,...,2425.170706,227.008810,225.800797,414,379,0.915459,406,379,0.933498,0
0,196.866048,221.196286,0.689655,894.425729,1043.504642,3.010884e+05,0.0,193.234416,215.691976,0.778515,...,2208.740501,201.022387,206.475180,370,341,0.921622,376,337,0.896277,0
0,193.465046,205.356636,0.626140,917.348531,824.533941,1.732871e+09,0.0,181.697062,196.308004,0.500507,...,1807.705443,200.010000,192.166594,370,342,0.924324,298,341,1.144295,0

In [475]:
def normalize(data):
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    output_columns = ["label"] 
    x=df.drop(output_columns,axis=1).columns.tolist()
    for feature in x:
        data[feature] = scaler.fit_transform(data[feature].values.reshape(-1,1))
    return data
df.head()

,X_S_Mean,Y_S_Mean,Z_S_Mean,Pressure_S_Mean,GripAngle_S_Mean,Timestamp_S_Mean,TestID_S_Mean,X_D_Mean,Y_D_Mean,Z_D_Mean,...,totalPath_D,RadMax_S,RadMax_D,Xmax_S,Ymax_S,AR_S,Xmax_D,Ymax_D,AR_D,label
0,199.736230,204.876649,0.721490,884.200931,794.317300,1.732656e+09,0.0,180.819240,187.094259,0.488751,...,1704.523001,201.039797,167.502239,371,337,0.908356,286,262,0.916084,0
0,191.760360,213.143844,0.727928,787.918619,782.852853,1.732477e+09,0.0,200.569970,213.618318,0.559760,...,2161.128124,198.156504,203.039405,343,337,0.982507,365,336,0.920548,0
0,230.687263,252.600152,0.717144,843.550013,903.502152,1.300956e+06,0.0,214.136997,247.773867,0.750570,...,2425.170706,227.008810,225.800797,414,379,0.915459,406,379,0.933498,0
0,196.866048,221.196286,0.689655,894.425729,1043.504642,3.010884e+05,0.0,193.234416,215.691976,0.778515,...,2208.740501,201.022387,206.475180,370,341,0.921622,376,337,0.896277,0
0,193.465046,205.356636,0.626140,917.348531,824.533941,1.732871e+09,0.0,181.697062,196.308004,0.500507,...,1807.705443,200.010000,192.166594,370,342,0.924324,298,341,1.144295,0

In [476]:
df=normalize(df)
df.head()

,X_S_Mean,Y_S_Mean,Z_S_Mean,Pressure_S_Mean,GripAngle_S_Mean,Timestamp_S_Mean,TestID_S_Mean,X_D_Mean,Y_D_Mean,Z_D_Mean,...,totalPath_D,RadMax_S,RadMax_D,Xmax_S,Ymax_S,AR_S,Xmax_D,Ymax_D,AR_D,label
0,-0.503417,-0.389901,1.047314,1.465872,-0.912537,1.295375,0.0,-0.861897,-1.961317,0.324845,...,-0.610323,-0.022508,-0.750746,0.202143,0.644019,0.094036,-0.725578,-0.878084,0.251182,0
0,-0.656574,0.129405,1.064880,0.852635,-0.940621,1.295168,0.0,-0.537784,0.026864,0.497585,...,-0.016094,-0.081202,-0.246308,-0.086879,0.644019,0.577453,-0.031600,0.636462,0.276411,0
0,0.090926,2.607866,1.035457,1.206960,-0.645076,-0.700921,0.0,-0.315147,2.587084,0.961761,...,0.327534,0.506138,0.076783,0.645998,1.432166,0.140343,0.328566,1.516535,0.349598,0
0,-0.558532,0.635222,0.960458,1.530995,-0.302122,-0.702074,0.0,-0.658161,0.182301,1.029741,...,0.045869,-0.022862,-0.197538,0.191821,0.719080,0.180520,0.065030,0.656928,0.139239,0
0,-0.623840,-0.359751,0.787165,1.676994,-0.838518,1.295623,0.0,-0.847491,-1.270676,0.353442,...,-0.476041,-0.043471,-0.400644,0.191821,0.737846,0.198139,-0.620164,0.738796,1.540949,0

In [477]:
df.to_csv('data/processed/all.csv',index=False)